import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Bot, 
  Send, 
  BookOpen,
  RefreshCw
} from 'lucide-react';
import ShinyText from '../text/ShinyText';

interface Message {
  sender: 'user' | 'agent';
  text: string;
  isStreaming?: boolean;
}

export default function AIDemoSection() {
  const [messages, setMessages] = useState<Message[]>([
    {
      sender: 'agent',
      text: "Hello! I am your AI Chartered Accountant. Select the sample query below or type your own to see how I analyze portfolios and construct legally citable tax minimization reports."
    }
  ]);
  const [inputVal, setInputVal] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const samplePrompts = [
    "I sold stocks and have salary income. How can I reduce my taxes legally?",
    "Can I claim HRA if I pay rent to my parents, and is landlord PAN required?",
    "Suggest tax optimization gaps for a salary of ₹15 Lakhs and ₹2 Lakhs home loan interest."
  ];

  // Auto scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isTyping]);

  const triggerSimulation = async (queryText: string) => {
    if (isTyping) return;
    
    // Add user message
    setMessages(prev => [...prev, { sender: 'user', text: queryText }]);
    setIsTyping(true);

    // Simulate response delay
    await new Promise(resolve => setTimeout(resolve, 1500));

    let replyMemo = '';
    if (queryText.includes('sold stocks')) {
      replyMemo = `# CHARTERED ACCOUNTANT ADVISORY MEMO

**Subject:** Capital Gains & Salary Income Tax Optimisation  
**Tax Jurisdiction:** Indian Income Tax Act, 1961 (AY 2025-26)

## 1. Executive Summary
We have analyzed your portfolio consisting of Salary Income and Equity transactions. To minimize tax liabilities legally, we recommend filing under the **NEW Tax Regime (u/s 115BAC)**. 

## 2. Capital Gains Tax Treatment
* **Short-Term Capital Gains (STCG) u/s 111A**: Listed equity sold within 12 months is taxed at **20% flat** (raised from 15% in Budget 2024).
* **Long-Term Capital Gains (LTCG) u/s 112A**: Listed equity held >12 months is taxed at **12.5% flat** (raised from 10%), with an increased tax-free exemption threshold of **₹1,25,000** (previously ₹1 Lakh).

## 3. Tax Minimization Strategies
* **Tax-Loss Harvesting**: Offset STCG losses against STCG/LTCG gains before March 31 to lower net taxable gains.
* **Employer NPS (u/s 80CCD(2))**: Request your employer to restructure up to 10% of your Basic+DA into NPS. This deduction remains fully available under the **New Tax Regime**.

---
*Disclaimer: Generated by Virtual CA. Verify details with a human professional.*`;
    } else if (queryText.includes('parents')) {
      replyMemo = `# CHARTERED ACCOUNTANT ADVISORY MEMO

**Subject:** HRA Exemption on Rent Paid to Parents  
**Statutory Reference:** Section 10(13A) read with Rule 2A

## 1. Legality of Claim
Yes, you can legally pay rent to your parents and claim the HRA exemption, provided they own the property and declare the rent as "Income from House Property" in their own tax returns.

## 2. Compliance Checklist
* **Landlord PAN Requirement**: Since your annual rent exceeds **₹1,00,000**, you **must** obtain and declare your parent's PAN in Form 12BB.
* **Rent Receipts & Agreement**: Maintain registered rent receipts and a formal lease agreement.
* **Actual Money Transfer**: Ensure actual banking transactions (no cash payment without tracking) to avoid rejection during IT audits.

---
*Disclaimer: Generated by Virtual CA. Verify details with a human professional.*`;
    } else {
      replyMemo = `# CHARTERED ACCOUNTANT ADVISORY MEMO

**Subject:** Slabs Optimization & Housing Interest Set-off  
**Statutory Reference:** Section 24(b) & Section 80C

## 1. Regime Comparison
* **Old Tax Regime**: You can claim Section 24(b) home loan interest deduction up to **₹2,00,000** and Section 80C up to **₹1,50,000**.
* **New Tax Regime**: Home loan interest u/s 24(b) on **Self-Occupied property** is NOT deductible. However, if the property is **Let-Out**, interest is fully deductible against rental income.

## 2. Gap Recommendation
Maximize your Chapter VI-A deductions if opting for the Old Regime. You currently have an unused gap of **₹30,000** in Section 80C. Invest in ELSS or PPF to maximize your returns.

---
*Disclaimer: Generated by Virtual CA. Verify details with a human professional.*`;
    }

    setIsTyping(false);
    setMessages(prev => [...prev, { sender: 'agent', text: replyMemo }]);
  };

  const handleSend = (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputVal.trim() || isTyping) return;
    const text = inputVal;
    setInputVal('');
    triggerSimulation(text);
  };

  return (
    <section id="demo" className="w-full py-16 px-6 md:px-12 relative flex flex-col items-center justify-center">
      {/* Title Header */}
      <div className="text-center flex flex-col items-center gap-3 max-w-xl mb-16">
        <span className="text-xs font-semibold tracking-wider text-blue-400 uppercase">INTERACTIVE DEMO</span>
        <h2 className="text-3xl md:text-4xl font-bold text-white tracking-tight">
          Test drive the AI CA Co-Pilot
        </h2>
        <p className="text-sm text-slate-400 leading-relaxed mt-1">
          Interact with the chat simulator to see how the Virtual CA parses inputs and drafts citable tax memos.
        </p>
      </div>

      {/* Chat Interface Console wrapper */}
      <div className="w-full max-w-4xl relative z-10 flex flex-col gap-6 items-center">
        
        {/* Preset Prompt Selectors */}
        <div className="w-full flex flex-col gap-2 items-start max-w-3xl">
          <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">Try an Example Query</span>
          <div className="w-full flex flex-wrap gap-2.5">
            {samplePrompts.map((prompt, idx) => (
              <button
                key={idx}
                onClick={() => triggerSimulation(prompt)}
                disabled={isTyping}
                className="text-xs text-left px-4 py-2.5 bg-slate-900/40 hover:bg-slate-900 border border-slate-800/80 hover:border-blue-500/20 text-slate-300 hover:text-white rounded-xl transition-all duration-200 cursor-pointer max-w-full truncate disabled:opacity-50 disabled:pointer-events-none"
              >
                {prompt}
              </button>
            ))}
          </div>
        </div>

        {/* The Mock Terminal Chat Console */}
        <div className="w-full max-w-3xl bg-slate-950/60 border border-slate-800/80 rounded-2xl shadow-2xl overflow-hidden backdrop-blur-xl flex flex-col h-[480px]">
          
          {/* Header Bar */}
          <div className="p-4 border-b border-slate-800/60 bg-slate-900/20 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="w-2.5 h-2.5 bg-red-500 rounded-full" />
              <span className="w-2.5 h-2.5 bg-yellow-500 rounded-full" />
              <span className="w-2.5 h-2.5 bg-green-500 rounded-full" />
              <div className="h-4 w-px bg-slate-800 mx-2" />
              <span className="text-xs text-slate-400 font-medium flex items-center gap-1.5">
                <Bot className="h-4 w-4 text-blue-400" />
                Virtual CA Session
              </span>
            </div>
            <button 
              onClick={() => setMessages([{ sender: 'agent', text: "Hello! I am your AI Chartered Accountant. Select the sample query below or type your own to see how I analyze portfolios." }])}
              className="text-[10px] text-slate-500 hover:text-slate-300 transition-colors flex items-center gap-1 cursor-pointer"
            >
              <RefreshCw className="h-3 w-3" />
              Reset Console
            </button>
          </div>

          {/* Message List area */}
          <div className="flex-1 p-6 overflow-y-auto flex flex-col gap-6">
            <AnimatePresence initial={false}>
              {messages.map((msg, index) => {
                const isUser = msg.sender === 'user';
                return (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, y: 15 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.3 }}
                    className={`flex ${isUser ? 'justify-end' : 'justify-start'}`}
                  >
                    <div className={`max-w-[85%] sm:max-w-[75%] p-5 rounded-2xl ${
                      isUser 
                        ? 'bg-blue-600 text-white rounded-tr-none shadow-lg shadow-blue-600/10' 
                        : 'bg-slate-900/60 border border-slate-800/80 text-slate-200 rounded-tl-none'
                    }`}>
                      {isUser ? (
                        <p className="text-sm leading-relaxed whitespace-pre-wrap">{msg.text}</p>
                      ) : (
                        <div className="text-sm leading-relaxed space-y-4 whitespace-pre-wrap text-left">
                          {msg.text.split('\n\n').map((block, bIdx) => {
                            if (block.startsWith('# ')) {
                              return <h1 key={bIdx} className="text-base font-bold text-white border-b border-slate-800 pb-2">{block.replace('# ', '')}</h1>
                            }
                            if (block.startsWith('## ')) {
                              return <h2 key={bIdx} className="text-sm font-semibold text-white pt-2 flex items-center gap-1.5"><BookOpen className="h-4 w-4 text-blue-400" />{block.replace('## ', '')}</h2>
                            }
                            if (block.startsWith('* ')) {
                              return (
                                <ul key={bIdx} className="list-disc pl-5 space-y-1">
                                  {block.split('\n').map((li, lIdx) => (
                                    <li key={lIdx} className="text-slate-350">{li.replace('* ', '')}</li>
                                  ))}
                                </ul>
                              )
                            }
                            return <p key={bIdx} className="text-slate-300">{block}</p>
                          })}
                        </div>
                      )}
                    </div>
                  </motion.div>
                );
              })}
            </AnimatePresence>

            {/* Typing Loader */}
            {isTyping && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="flex justify-start"
              >
                <div className="p-4 bg-slate-900/60 border border-slate-800/80 rounded-2xl rounded-tl-none flex items-center gap-3">
                  <div className="flex gap-1.5">
                    <span className="w-2 h-2 bg-blue-500 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                    <span className="w-2 h-2 bg-blue-500 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                    <span className="w-2 h-2 bg-blue-500 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                  </div>
                  <span className="text-[10px] text-slate-500 font-bold tracking-wider uppercase flex items-center gap-1">
                    <ShinyText text="Virtual CA is analyzing legal database..." speed={2.5} shineColor="#60a5fa" color="#64748b" className="inline" />
                  </span>
                </div>
              </motion.div>
            )}
            <div ref={messagesEndRef} />
          </div>

          {/* Chat Form Input */}
          <form onSubmit={handleSend} className="p-4 border-t border-slate-800/60 bg-slate-900/20 flex gap-2">
            <input
              type="text"
              value={inputVal}
              onChange={(e) => setInputVal(e.target.value)}
              placeholder="Ask a question (e.g. 'Is home loan principal deductible?')"
              disabled={isTyping}
              className="flex-1 bg-slate-950/80 border border-slate-800 rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-blue-500/40 text-slate-200 placeholder-slate-500 disabled:opacity-50"
            />
            <button
              type="submit"
              disabled={isTyping}
              className="bg-blue-600 hover:bg-blue-500 disabled:opacity-50 px-5 py-3 rounded-xl text-sm font-semibold transition-all duration-200 shadow-lg shadow-blue-600/20 flex items-center justify-center cursor-pointer shrink-0"
            >
              <Send className="h-4 w-4 text-white" />
            </button>
          </form>

        </div>
      </div>
    </section>
  );
}
